version: '3.4'

services:
  icalingua:
    image: icalingua
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command:
      [
        "pnpm",
        "dev:backend",
        "--",
        "--inspect=0.0.0.0:9229",
        "-h",
        "0.0.0.0"
      ]
