version: '3.4'

services:
  icalingua3:
    image: ghcr.io/icalingua-plus-plus/icalingua3
    container_name: icalingua3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./data:/usr/src/app/data
